# pyright: reportUnknownArgumentType=false
"""initial schema

Revision ID: 18cd31149b5d
Revises:
Create Date: 2026-07-07 15:27:28.118389

"""

from collections.abc import Sequence  # noqa: TC003

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "18cd31149b5d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "document",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "website_page",
                "website_program",
                "catalog_page",
                "catalog_program",
                "catalog_course",
                "training_material",
                name="document_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("source_key", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("markdown_content", sa.String(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("title_embedding", Vector(2000), nullable=False),
        sa.Column("school", sa.String(), nullable=True),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_document_title_embedding",
        "document",
        ["title_embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"title_embedding": "vector_l2_ops"},
    )
    op.create_index(op.f("ix_document_source_key"), "document", ["source_key"], unique=True)
    op.create_table(
        "eval_run_record",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.String(length=255), nullable=False),
        sa.Column("suite", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("repeats", sa.Integer(), nullable=False),
        sa.Column("max_concurrency", sa.Integer(), nullable=False),
        sa.Column("pass_threshold", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("log_id", sa.String(length=255), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_configs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("additional_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_eval_run_record_generated_at"), "eval_run_record", ["generated_at"], unique=False
    )
    op.create_index(op.f("ix_eval_run_record_name"), "eval_run_record", ["name"], unique=False)
    op.create_index(
        op.f("ix_eval_run_record_report_id"), "eval_run_record", ["report_id"], unique=True
    )
    op.create_index(op.f("ix_eval_run_record_status"), "eval_run_record", ["status"], unique=False)
    op.create_index(op.f("ix_eval_run_record_suite"), "eval_run_record", ["suite"], unique=False)
    op.create_table(
        "guardrail_url_registry",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("urls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_guardrail_url_registry_key"), "guardrail_url_registry", ["key"], unique=True
    )
    op.create_table(
        "otel_span",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.String(), nullable=False),
        sa.Column("span_id", sa.String(), nullable=False),
        sa.Column("parent_span_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=True),
        sa.Column("status_code", sa.String(), nullable=True),
        sa.Column("status_message", sa.Text(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("events", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("links", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("resource", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("span_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("request_model", sa.String(), nullable=True),
        sa.Column("provider_name", sa.String(), nullable=True),
        sa.Column("server_address", sa.String(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("total_cost", sa.Float(), nullable=True),
        sa.Column("is_ai", sa.Boolean(), nullable=False),
        sa.Column("is_embedding", sa.Boolean(), nullable=True),
        sa.Column("is_internal", sa.Boolean(), nullable=True),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("total_time", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_otel_span_conversation_id"), "otel_span", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_otel_span_is_ai"), "otel_span", ["is_ai"], unique=False)
    op.create_index(op.f("ix_otel_span_message_id"), "otel_span", ["message_id"], unique=False)
    op.create_index(
        op.f("ix_otel_span_parent_span_id"), "otel_span", ["parent_span_id"], unique=False
    )
    op.create_index(
        op.f("ix_otel_span_request_model"), "otel_span", ["request_model"], unique=False
    )
    op.create_index(op.f("ix_otel_span_span_id"), "otel_span", ["span_id"], unique=False)
    op.create_index(op.f("ix_otel_span_trace_id"), "otel_span", ["trace_id"], unique=False)
    op.create_table(
        "rbac_group",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rbac_group_slug"), "rbac_group", ["slug"], unique=True)
    op.create_table(
        "document_content_chunk",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("content_embedding", Vector(2000), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_document_content_chunk_content_embedding",
        "document_content_chunk",
        ["content_embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"content_embedding": "vector_l2_ops"},
    )
    op.create_index(
        op.f("ix_document_content_chunk_document_id"),
        "document_content_chunk",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "eval_case_result",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("eval_run_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["eval_run_id"], ["eval_run_record.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_eval_case_result_eval_run_id"), "eval_case_result", ["eval_run_id"], unique=False
    )
    op.create_index(op.f("ix_eval_case_result_name"), "eval_case_result", ["name"], unique=False)
    op.create_index(
        "ix_eval_case_result_run_position",
        "eval_case_result",
        ["eval_run_id", "position"],
        unique=False,
    )
    op.create_table(
        "rbac_group_permission",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("permission_key", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["rbac_group.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rbac_group_permission_group_id"),
        "rbac_group_permission",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        "ix_rbac_group_permission_group_permission",
        "rbac_group_permission",
        ["group_id", "permission_key"],
        unique=True,
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("entra_tenant_id", sa.String(length=64), nullable=True),
        sa.Column("entra_object_id", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["rbac_group.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(
        "ix_user_entra_identity", "user", ["entra_tenant_id", "entra_object_id"], unique=True
    )
    op.create_index(op.f("ix_user_group_id"), "user", ["group_id"], unique=False)
    op.create_table(
        "conversation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("user", sa.Boolean(), nullable=False),
        sa.Column("project", sa.String(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("investigation_source_conversation_id", sa.Uuid(), nullable=True),
        sa.Column("investigation_source_message_id", sa.Uuid(), nullable=True),
        sa.Column("investigation_source_feedback_id", sa.Uuid(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["investigation_source_conversation_id"],
            ["conversation.id"],
            name="fk_conversation_investigation_source_conversation_id",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["investigation_source_feedback_id"],
            ["message_feedback.id"],
            name="fk_conversation_investigation_source_feedback_id",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["investigation_source_message_id"],
            ["message.id"],
            name="fk_conversation_investigation_source_message_id",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_investigation_source_conversation_id"),
        "conversation",
        ["investigation_source_conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_investigation_source_feedback_id"),
        "conversation",
        ["investigation_source_feedback_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_investigation_source_message_id"),
        "conversation",
        ["investigation_source_message_id"],
        unique=False,
    )
    op.create_index(op.f("ix_conversation_is_public"), "conversation", ["is_public"], unique=False)
    op.create_index(op.f("ix_conversation_kind"), "conversation", ["kind"], unique=False)
    op.create_index(op.f("ix_conversation_user_id"), "conversation", ["user_id"], unique=False)
    op.create_table(
        "eval_case_run_result",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("run_index", sa.Integer(), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("otel_trace_id", sa.String(length=64), nullable=True),
        sa.Column("otel_span_id", sa.String(length=32), nullable=True),
        sa.Column("assertions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["eval_case_result.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_eval_case_run_result_case_id"), "eval_case_run_result", ["case_id"], unique=False
    )
    op.create_index(
        "ix_eval_case_run_result_case_run",
        "eval_case_run_result",
        ["case_id", "run_index"],
        unique=False,
    )
    op.create_index(
        op.f("ix_eval_case_run_result_otel_span_id"),
        "eval_case_run_result",
        ["otel_span_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_eval_case_run_result_otel_trace_id"),
        "eval_case_run_result",
        ["otel_trace_id"],
        unique=False,
    )
    op.create_table(
        "eval_test_case_overlay",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("suite", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=255), nullable=False),
        sa.Column("case_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("base_disk_hash", sa.String(length=64), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_eval_test_case_overlay_case_id"),
        "eval_test_case_overlay",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_eval_test_case_overlay_created_by_user_id"),
        "eval_test_case_overlay",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_eval_test_case_overlay_suite"), "eval_test_case_overlay", ["suite"], unique=False
    )
    op.create_index(
        "ix_eval_test_case_overlay_suite_case",
        "eval_test_case_overlay",
        ["suite", "case_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_eval_test_case_overlay_updated_by_user_id"),
        "eval_test_case_overlay",
        ["updated_by_user_id"],
        unique=False,
    )
    op.create_table(
        "prompt_set_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("is_internal", sa.Boolean(), nullable=False),
        sa.Column(
            "scope",
            sa.Enum(
                "assistant",
                "investigation",
                "summary",
                "title",
                "title_transcript",
                "grounding",
                name="prompt_set_scope",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_deployed", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prompt_set_version_created_by_id"),
        "prompt_set_version",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_set_version_is_deployed"),
        "prompt_set_version",
        ["is_deployed"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_set_version_is_internal"),
        "prompt_set_version",
        ["is_internal"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_set_version_scope"), "prompt_set_version", ["scope"], unique=False
    )
    op.create_table(
        "rag_build_job",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_name", sa.String(length=128), nullable=False),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("force_rebuild", sa.Boolean(), nullable=False),
        sa.Column("started_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("current_step", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["started_by_user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rag_build_job_finished_at"), "rag_build_job", ["finished_at"], unique=False
    )
    op.create_index(op.f("ix_rag_build_job_job_name"), "rag_build_job", ["job_name"], unique=False)
    op.create_index(
        op.f("ix_rag_build_job_started_at"), "rag_build_job", ["started_at"], unique=False
    )
    op.create_index(
        op.f("ix_rag_build_job_started_by_user_id"),
        "rag_build_job",
        ["started_by_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_rag_build_job_status"), "rag_build_job", ["status"], unique=False)
    op.create_index(
        "ix_rag_build_job_status_started", "rag_build_job", ["status", "started_at"], unique=False
    )
    op.create_index(op.f("ix_rag_build_job_trigger"), "rag_build_job", ["trigger"], unique=False)
    op.create_table(
        "rag_document_exclusion",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_key", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rag_document_exclusion_created_by_user_id"),
        "rag_document_exclusion",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rag_document_exclusion_source_key"),
        "rag_document_exclusion",
        ["source_key"],
        unique=True,
    )
    op.create_table(
        "rag_document_exclusion_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_key", sa.String(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("document_title", sa.String(), nullable=True),
        sa.Column("document_url", sa.String(), nullable=True),
        sa.Column("source_type", sa.String(length=64), nullable=True),
        sa.Column("actor_name", sa.String(), nullable=True),
        sa.Column("actor_email", sa.String(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rag_document_exclusion_event_action"),
        "rag_document_exclusion_event",
        ["action"],
        unique=False,
    )
    op.create_index(
        "ix_rag_document_exclusion_event_created_at",
        "rag_document_exclusion_event",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rag_document_exclusion_event_created_by_user_id"),
        "rag_document_exclusion_event",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rag_document_exclusion_event_source_key"),
        "rag_document_exclusion_event",
        ["source_key"],
        unique=False,
    )
    op.create_table(
        "rbac_user_permission_override",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("permission_key", sa.String(length=128), nullable=False),
        sa.Column("is_allowed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rbac_user_permission_override_user_id"),
        "rbac_user_permission_override",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_rbac_user_permission_override_user_permission",
        "rbac_user_permission_override",
        ["user_id", "permission_key"],
        unique=True,
    )
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_token_hash", sa.String(length=128), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_token_token_hash"), "refresh_token", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_refresh_token_user_id"), "refresh_token", ["user_id"], unique=False)
    op.create_table(
        "conversation_feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "rating", sa.Enum("thumbs_up", "thumbs_down", name="rating_enum"), nullable=False
        ),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversation.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_feedback_conversation_id"),
        "conversation_feedback",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_feedback_user_id"), "conversation_feedback", ["user_id"], unique=False
    )
    op.create_table(
        "message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("guardrails_blocked", sa.Boolean(), nullable=False),
        sa.Column("guardrails_blocked_message", sa.Text(), nullable=True),
        sa.Column("active_child_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["active_child_id"], ["message.id"]),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversation.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["message.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_message_active_child_id"), "message", ["active_child_id"], unique=False
    )
    op.create_index(
        op.f("ix_message_conversation_id"), "message", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_message_parent_id"), "message", ["parent_id"], unique=False)
    op.create_table(
        "prompt_set_template",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("prompt_set_version_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["prompt_set_version_id"], ["prompt_set_version.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_prompt_set_template_version_filename",
        "prompt_set_template",
        ["prompt_set_version_id", "filename"],
        unique=True,
    )
    op.create_index(
        op.f("ix_prompt_set_template_prompt_set_version_id"),
        "prompt_set_template",
        ["prompt_set_version_id"],
        unique=False,
    )
    op.create_table(
        "public_chat_contact",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("zip", sa.String(), nullable=False),
        sa.Column("visitor_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("consented_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("environment", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversation.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_public_chat_contact_conversation_unique",
        "public_chat_contact",
        ["conversation_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_public_chat_contact_email"), "public_chat_contact", ["email"], unique=False
    )
    op.create_index(
        "ix_public_chat_contact_visitor_conversation",
        "public_chat_contact",
        ["visitor_id", "conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_public_chat_contact_visitor_id"),
        "public_chat_contact",
        ["visitor_id"],
        unique=False,
    )
    op.create_table(
        "rag_build_job_document_change",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("source_name", sa.String(length=128), nullable=False),
        sa.Column("document_type", sa.String(length=64), nullable=False),
        sa.Column("change_type", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("source_key", sa.String(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("previous_title", sa.Text(), nullable=True),
        sa.Column("previous_url", sa.Text(), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("previous_source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["rag_build_job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rag_build_job_document_change_change_type"),
        "rag_build_job_document_change",
        ["change_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rag_build_job_document_change_document_type"),
        "rag_build_job_document_change",
        ["document_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rag_build_job_document_change_job_id"),
        "rag_build_job_document_change",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        "ix_rag_build_job_document_change_job_type",
        "rag_build_job_document_change",
        ["job_id", "change_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rag_build_job_document_change_source_name"),
        "rag_build_job_document_change",
        ["source_name"],
        unique=False,
    )
    op.create_table(
        "rag_build_job_source_stat",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("source_name", sa.String(length=128), nullable=False),
        sa.Column("document_type", sa.String(length=64), nullable=False),
        sa.Column("new_count", sa.Integer(), nullable=False),
        sa.Column("changed_count", sa.Integer(), nullable=False),
        sa.Column("deleted_count", sa.Integer(), nullable=False),
        sa.Column("unchanged_count", sa.Integer(), nullable=False),
        sa.Column("source_document_count", sa.Integer(), nullable=False),
        sa.Column("existing_document_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["rag_build_job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rag_build_job_source_stat_document_type"),
        "rag_build_job_source_stat",
        ["document_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rag_build_job_source_stat_job_id"),
        "rag_build_job_source_stat",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        "ix_rag_build_job_source_stat_unique",
        "rag_build_job_source_stat",
        ["job_id", "source_name", "document_type"],
        unique=True,
    )
    op.create_table(
        "rag_build_job_step",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("step_key", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["rag_build_job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rag_build_job_step_job_id"), "rag_build_job_step", ["job_id"], unique=False
    )
    op.create_index(
        "ix_rag_build_job_step_job_key", "rag_build_job_step", ["job_id", "step_key"], unique=True
    )
    op.create_index(
        op.f("ix_rag_build_job_step_status"), "rag_build_job_step", ["status"], unique=False
    )
    op.create_table(
        "assistant_message_metadata",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("tool_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("guardrails", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("system_prompt_rendered", sa.String(), nullable=False),
        sa.Column("conversation_turn", sa.Integer(), nullable=False),
        sa.Column("total_time", sa.Float(), nullable=True),
        sa.Column(
            "guardrail_model_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("guardrail_time", sa.Float(), nullable=True),
        sa.Column("chatbot_times", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("guardrail_times", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("grounding_source_keys", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("grounding_source_status", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["message.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assistant_message_metadata_message_id"),
        "assistant_message_metadata",
        ["message_id"],
        unique=True,
    )
    op.create_table(
        "message_feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "rating", sa.Enum("thumbs_up", "thumbs_down", name="rating_enum"), nullable=False
        ),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["message.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_message_feedback_message_id"), "message_feedback", ["message_id"], unique=False
    )
    op.create_index(
        op.f("ix_message_feedback_user_id"), "message_feedback", ["user_id"], unique=False
    )
    op.create_foreign_key(
        "fk_conversation_investigation_source_feedback_id",
        "conversation",
        "message_feedback",
        ["investigation_source_feedback_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_conversation_investigation_source_message_id",
        "conversation",
        "message",
        ["investigation_source_message_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_conversation_investigation_source_conversation_id",
        "conversation",
        "conversation",
        ["investigation_source_conversation_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_conversation_investigation_source_feedback_id", "conversation", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_conversation_investigation_source_message_id", "conversation", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_conversation_investigation_source_conversation_id", "conversation", type_="foreignkey"
    )
    op.drop_index(op.f("ix_message_feedback_user_id"), table_name="message_feedback")
    op.drop_index(op.f("ix_message_feedback_message_id"), table_name="message_feedback")
    op.drop_table("message_feedback")
    op.drop_index(
        op.f("ix_assistant_message_metadata_message_id"), table_name="assistant_message_metadata"
    )
    op.drop_table("assistant_message_metadata")
    op.drop_index(op.f("ix_rag_build_job_step_status"), table_name="rag_build_job_step")
    op.drop_index("ix_rag_build_job_step_job_key", table_name="rag_build_job_step")
    op.drop_index(op.f("ix_rag_build_job_step_job_id"), table_name="rag_build_job_step")
    op.drop_table("rag_build_job_step")
    op.drop_index("ix_rag_build_job_source_stat_unique", table_name="rag_build_job_source_stat")
    op.drop_index(
        op.f("ix_rag_build_job_source_stat_job_id"), table_name="rag_build_job_source_stat"
    )
    op.drop_index(
        op.f("ix_rag_build_job_source_stat_document_type"), table_name="rag_build_job_source_stat"
    )
    op.drop_table("rag_build_job_source_stat")
    op.drop_index(
        op.f("ix_rag_build_job_document_change_source_name"),
        table_name="rag_build_job_document_change",
    )
    op.drop_index(
        "ix_rag_build_job_document_change_job_type", table_name="rag_build_job_document_change"
    )
    op.drop_index(
        op.f("ix_rag_build_job_document_change_job_id"), table_name="rag_build_job_document_change"
    )
    op.drop_index(
        op.f("ix_rag_build_job_document_change_document_type"),
        table_name="rag_build_job_document_change",
    )
    op.drop_index(
        op.f("ix_rag_build_job_document_change_change_type"),
        table_name="rag_build_job_document_change",
    )
    op.drop_table("rag_build_job_document_change")
    op.drop_index(op.f("ix_public_chat_contact_visitor_id"), table_name="public_chat_contact")
    op.drop_index("ix_public_chat_contact_visitor_conversation", table_name="public_chat_contact")
    op.drop_index(op.f("ix_public_chat_contact_email"), table_name="public_chat_contact")
    op.drop_index("ix_public_chat_contact_conversation_unique", table_name="public_chat_contact")
    op.drop_table("public_chat_contact")
    op.drop_index(
        op.f("ix_prompt_set_template_prompt_set_version_id"), table_name="prompt_set_template"
    )
    op.drop_index("idx_prompt_set_template_version_filename", table_name="prompt_set_template")
    op.drop_table("prompt_set_template")
    op.drop_index(op.f("ix_message_parent_id"), table_name="message")
    op.drop_index(op.f("ix_message_conversation_id"), table_name="message")
    op.drop_index(op.f("ix_message_active_child_id"), table_name="message")
    op.drop_table("message")
    op.drop_index(op.f("ix_conversation_feedback_user_id"), table_name="conversation_feedback")
    op.drop_index(
        op.f("ix_conversation_feedback_conversation_id"), table_name="conversation_feedback"
    )
    op.drop_table("conversation_feedback")
    op.drop_index(op.f("ix_refresh_token_user_id"), table_name="refresh_token")
    op.drop_index(op.f("ix_refresh_token_token_hash"), table_name="refresh_token")
    op.drop_table("refresh_token")
    op.drop_index(
        "ix_rbac_user_permission_override_user_permission",
        table_name="rbac_user_permission_override",
    )
    op.drop_index(
        op.f("ix_rbac_user_permission_override_user_id"), table_name="rbac_user_permission_override"
    )
    op.drop_table("rbac_user_permission_override")
    op.drop_index(
        op.f("ix_rag_document_exclusion_event_source_key"),
        table_name="rag_document_exclusion_event",
    )
    op.drop_index(
        op.f("ix_rag_document_exclusion_event_created_by_user_id"),
        table_name="rag_document_exclusion_event",
    )
    op.drop_index(
        "ix_rag_document_exclusion_event_created_at", table_name="rag_document_exclusion_event"
    )
    op.drop_index(
        op.f("ix_rag_document_exclusion_event_action"), table_name="rag_document_exclusion_event"
    )
    op.drop_table("rag_document_exclusion_event")
    op.drop_index(op.f("ix_rag_document_exclusion_source_key"), table_name="rag_document_exclusion")
    op.drop_index(
        op.f("ix_rag_document_exclusion_created_by_user_id"), table_name="rag_document_exclusion"
    )
    op.drop_table("rag_document_exclusion")
    op.drop_index(op.f("ix_rag_build_job_trigger"), table_name="rag_build_job")
    op.drop_index("ix_rag_build_job_status_started", table_name="rag_build_job")
    op.drop_index(op.f("ix_rag_build_job_status"), table_name="rag_build_job")
    op.drop_index(op.f("ix_rag_build_job_started_by_user_id"), table_name="rag_build_job")
    op.drop_index(op.f("ix_rag_build_job_started_at"), table_name="rag_build_job")
    op.drop_index(op.f("ix_rag_build_job_job_name"), table_name="rag_build_job")
    op.drop_index(op.f("ix_rag_build_job_finished_at"), table_name="rag_build_job")
    op.drop_table("rag_build_job")
    op.drop_index(op.f("ix_prompt_set_version_scope"), table_name="prompt_set_version")
    op.drop_index(op.f("ix_prompt_set_version_is_internal"), table_name="prompt_set_version")
    op.drop_index(op.f("ix_prompt_set_version_is_deployed"), table_name="prompt_set_version")
    op.drop_index(op.f("ix_prompt_set_version_created_by_id"), table_name="prompt_set_version")
    op.drop_table("prompt_set_version")
    op.drop_index(
        op.f("ix_eval_test_case_overlay_updated_by_user_id"), table_name="eval_test_case_overlay"
    )
    op.drop_index("ix_eval_test_case_overlay_suite_case", table_name="eval_test_case_overlay")
    op.drop_index(op.f("ix_eval_test_case_overlay_suite"), table_name="eval_test_case_overlay")
    op.drop_index(
        op.f("ix_eval_test_case_overlay_created_by_user_id"), table_name="eval_test_case_overlay"
    )
    op.drop_index(op.f("ix_eval_test_case_overlay_case_id"), table_name="eval_test_case_overlay")
    op.drop_table("eval_test_case_overlay")
    op.drop_index(op.f("ix_eval_case_run_result_otel_trace_id"), table_name="eval_case_run_result")
    op.drop_index(op.f("ix_eval_case_run_result_otel_span_id"), table_name="eval_case_run_result")
    op.drop_index("ix_eval_case_run_result_case_run", table_name="eval_case_run_result")
    op.drop_index(op.f("ix_eval_case_run_result_case_id"), table_name="eval_case_run_result")
    op.drop_table("eval_case_run_result")
    op.drop_index(op.f("ix_conversation_user_id"), table_name="conversation")
    op.drop_index(op.f("ix_conversation_kind"), table_name="conversation")
    op.drop_index(op.f("ix_conversation_is_public"), table_name="conversation")
    op.drop_index(
        op.f("ix_conversation_investigation_source_message_id"), table_name="conversation"
    )
    op.drop_index(
        op.f("ix_conversation_investigation_source_feedback_id"), table_name="conversation"
    )
    op.drop_index(
        op.f("ix_conversation_investigation_source_conversation_id"), table_name="conversation"
    )
    op.drop_table("conversation")
    op.drop_index(op.f("ix_user_group_id"), table_name="user")
    op.drop_index("ix_user_entra_identity", table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index("ix_rbac_group_permission_group_permission", table_name="rbac_group_permission")
    op.drop_index(op.f("ix_rbac_group_permission_group_id"), table_name="rbac_group_permission")
    op.drop_table("rbac_group_permission")
    op.drop_index("ix_eval_case_result_run_position", table_name="eval_case_result")
    op.drop_index(op.f("ix_eval_case_result_name"), table_name="eval_case_result")
    op.drop_index(op.f("ix_eval_case_result_eval_run_id"), table_name="eval_case_result")
    op.drop_table("eval_case_result")
    op.drop_index(
        op.f("ix_document_content_chunk_document_id"), table_name="document_content_chunk"
    )
    op.drop_index(
        "idx_document_content_chunk_content_embedding",
        table_name="document_content_chunk",
        postgresql_using="hnsw",
        postgresql_ops={"content_embedding": "vector_l2_ops"},
    )
    op.drop_table("document_content_chunk")
    op.drop_index(op.f("ix_rbac_group_slug"), table_name="rbac_group")
    op.drop_table("rbac_group")
    op.drop_index(op.f("ix_otel_span_trace_id"), table_name="otel_span")
    op.drop_index(op.f("ix_otel_span_span_id"), table_name="otel_span")
    op.drop_index(op.f("ix_otel_span_request_model"), table_name="otel_span")
    op.drop_index(op.f("ix_otel_span_parent_span_id"), table_name="otel_span")
    op.drop_index(op.f("ix_otel_span_message_id"), table_name="otel_span")
    op.drop_index(op.f("ix_otel_span_is_ai"), table_name="otel_span")
    op.drop_index(op.f("ix_otel_span_conversation_id"), table_name="otel_span")
    op.drop_table("otel_span")
    op.drop_index(op.f("ix_guardrail_url_registry_key"), table_name="guardrail_url_registry")
    op.drop_table("guardrail_url_registry")
    op.drop_index(op.f("ix_eval_run_record_suite"), table_name="eval_run_record")
    op.drop_index(op.f("ix_eval_run_record_status"), table_name="eval_run_record")
    op.drop_index(op.f("ix_eval_run_record_report_id"), table_name="eval_run_record")
    op.drop_index(op.f("ix_eval_run_record_name"), table_name="eval_run_record")
    op.drop_index(op.f("ix_eval_run_record_generated_at"), table_name="eval_run_record")
    op.drop_table("eval_run_record")
    op.drop_index(op.f("ix_document_source_key"), table_name="document")
    op.drop_index(
        "idx_document_title_embedding",
        table_name="document",
        postgresql_using="hnsw",
        postgresql_ops={"title_embedding": "vector_l2_ops"},
    )
    op.drop_table("document")
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
